/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface CourseMarketInterface extends utils.Interface {
  functions: {
    "addCourse(string,string,uint256)": FunctionFragment;
    "batchVerifyCourseCompletion(address[],string)": FunctionFragment;
    "certificate()": FunctionFragment;
    "courseCount()": FunctionFragment;
    "courses(uint256)": FunctionFragment;
    "hasCourse(address,string)": FunctionFragment;
    "owner()": FunctionFragment;
    "purchaseCourse(string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "userCourses(address,uint256)": FunctionFragment;
    "verifyCourseCompletion(address,string)": FunctionFragment;
    "web2ToCourseId(string)": FunctionFragment;
    "yiDengToken()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addCourse"
      | "batchVerifyCourseCompletion"
      | "certificate"
      | "courseCount"
      | "courses"
      | "hasCourse"
      | "owner"
      | "purchaseCourse"
      | "renounceOwnership"
      | "transferOwnership"
      | "userCourses"
      | "verifyCourseCompletion"
      | "web2ToCourseId"
      | "yiDengToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCourse",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchVerifyCourseCompletion",
    values: [string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "certificate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCourse",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userCourses",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCourseCompletion",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "web2ToCourseId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "yiDengToken",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchVerifyCourseCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasCourse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCourses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCourseCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "web2ToCourseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "yiDengToken",
    data: BytesLike
  ): Result;

  events: {
    "CourseAdded(uint256,string,string)": EventFragment;
    "CourseCompleted(address,uint256,uint256)": EventFragment;
    "CoursePurchased(address,uint256,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CourseAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CourseCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CoursePurchased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface CourseAddedEventObject {
  courseId: BigNumber;
  web2CourseId: string;
  name: string;
}
export type CourseAddedEvent = TypedEvent<
  [BigNumber, string, string],
  CourseAddedEventObject
>;

export type CourseAddedEventFilter = TypedEventFilter<CourseAddedEvent>;

export interface CourseCompletedEventObject {
  student: string;
  courseId: BigNumber;
  certificateId: BigNumber;
}
export type CourseCompletedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  CourseCompletedEventObject
>;

export type CourseCompletedEventFilter = TypedEventFilter<CourseCompletedEvent>;

export interface CoursePurchasedEventObject {
  buyer: string;
  courseId: BigNumber;
  web2CourseId: string;
}
export type CoursePurchasedEvent = TypedEvent<
  [string, BigNumber, string],
  CoursePurchasedEventObject
>;

export type CoursePurchasedEventFilter = TypedEventFilter<CoursePurchasedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface CourseMarket extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CourseMarketInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    batchVerifyCourseCompletion(
      students: string[],
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    certificate(overrides?: CallOverrides): Promise<[string]>;

    courseCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, string] & {
        web2CourseId: string;
        name: string;
        price: BigNumber;
        isActive: boolean;
        creator: string;
      }
    >;

    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    purchaseCourse(
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyCourseCompletion(
      student: string,
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    web2ToCourseId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    yiDengToken(overrides?: CallOverrides): Promise<[string]>;
  };

  addCourse(
    web2CourseId: string,
    name: string,
    price: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  batchVerifyCourseCompletion(
    students: string[],
    web2CourseId: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  certificate(overrides?: CallOverrides): Promise<string>;

  courseCount(overrides?: CallOverrides): Promise<BigNumber>;

  courses(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean, string] & {
      web2CourseId: string;
      name: string;
      price: BigNumber;
      isActive: boolean;
      creator: string;
    }
  >;

  hasCourse(
    user: string,
    web2CourseId: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  purchaseCourse(
    web2CourseId: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  userCourses(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyCourseCompletion(
    student: string,
    web2CourseId: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  web2ToCourseId(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  yiDengToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    batchVerifyCourseCompletion(
      students: string[],
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<void>;

    certificate(overrides?: CallOverrides): Promise<string>;

    courseCount(overrides?: CallOverrides): Promise<BigNumber>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean, string] & {
        web2CourseId: string;
        name: string;
        price: BigNumber;
        isActive: boolean;
        creator: string;
      }
    >;

    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    purchaseCourse(
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyCourseCompletion(
      student: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<void>;

    web2ToCourseId(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    yiDengToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CourseAdded(uint256,string,string)"(
      courseId?: BigNumberish | null,
      web2CourseId?: null,
      name?: null
    ): CourseAddedEventFilter;
    CourseAdded(
      courseId?: BigNumberish | null,
      web2CourseId?: null,
      name?: null
    ): CourseAddedEventFilter;

    "CourseCompleted(address,uint256,uint256)"(
      student?: string | null,
      courseId?: BigNumberish | null,
      certificateId?: null
    ): CourseCompletedEventFilter;
    CourseCompleted(
      student?: string | null,
      courseId?: BigNumberish | null,
      certificateId?: null
    ): CourseCompletedEventFilter;

    "CoursePurchased(address,uint256,string)"(
      buyer?: string | null,
      courseId?: BigNumberish | null,
      web2CourseId?: null
    ): CoursePurchasedEventFilter;
    CoursePurchased(
      buyer?: string | null,
      courseId?: BigNumberish | null,
      web2CourseId?: null
    ): CoursePurchasedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    batchVerifyCourseCompletion(
      students: string[],
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    certificate(overrides?: CallOverrides): Promise<BigNumber>;

    courseCount(overrides?: CallOverrides): Promise<BigNumber>;

    courses(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    purchaseCourse(
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyCourseCompletion(
      student: string,
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    web2ToCourseId(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    yiDengToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addCourse(
      web2CourseId: string,
      name: string,
      price: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    batchVerifyCourseCompletion(
      students: string[],
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    certificate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    courseCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasCourse(
      user: string,
      web2CourseId: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    purchaseCourse(
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    userCourses(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyCourseCompletion(
      student: string,
      web2CourseId: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    web2ToCourseId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    yiDengToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
