/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CourseCertificate } from "./CourseCertificate";
export type { CourseMarket } from "./CourseMarket";
export type { YiDengToken } from "./YiDengToken";
