/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface YiDengTokenInterface extends utils.Interface {
  functions: {
    "MAX_SUPPLY()": FunctionFragment;
    "TOKENS_PER_ETH()": FunctionFragment;
    "addSigner(address)": FunctionFragment;
    "allowance(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "buyWithETH()": FunctionFragment;
    "communityAllocation()": FunctionFragment;
    "decimals()": FunctionFragment;
    "decreaseAllowance(address,uint256)": FunctionFragment;
    "distributeInitialTokens(address,address,address)": FunctionFragment;
    "getSignerCount()": FunctionFragment;
    "hasSignedWithdrawal(uint256,address)": FunctionFragment;
    "increaseAllowance(address,uint256)": FunctionFragment;
    "initialDistributionDone()": FunctionFragment;
    "isSigner(address)": FunctionFragment;
    "marketingAllocation()": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "remainingMintableSupply()": FunctionFragment;
    "removeSigner(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requestWithdrawal(uint256,address)": FunctionFragment;
    "requiredSignatures()": FunctionFragment;
    "sellTokens(uint256)": FunctionFragment;
    "signWithdrawal(uint256)": FunctionFragment;
    "signers(uint256)": FunctionFragment;
    "symbol()": FunctionFragment;
    "teamAllocation()": FunctionFragment;
    "totalSupply()": FunctionFragment;
    "transfer(address,uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateRequiredSignatures(uint256)": FunctionFragment;
    "withdrawalId()": FunctionFragment;
    "withdrawalRequests(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MAX_SUPPLY"
      | "TOKENS_PER_ETH"
      | "addSigner"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "buyWithETH"
      | "communityAllocation"
      | "decimals"
      | "decreaseAllowance"
      | "distributeInitialTokens"
      | "getSignerCount"
      | "hasSignedWithdrawal"
      | "increaseAllowance"
      | "initialDistributionDone"
      | "isSigner"
      | "marketingAllocation"
      | "name"
      | "owner"
      | "remainingMintableSupply"
      | "removeSigner"
      | "renounceOwnership"
      | "requestWithdrawal"
      | "requiredSignatures"
      | "sellTokens"
      | "signWithdrawal"
      | "signers"
      | "symbol"
      | "teamAllocation"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
      | "updateRequiredSignatures"
      | "withdrawalId"
      | "withdrawalRequests"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MAX_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKENS_PER_ETH",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addSigner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "buyWithETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "communityAllocation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeInitialTokens",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSignedWithdrawal",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialDistributionDone",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isSigner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "marketingAllocation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remainingMintableSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeSigner",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredSignatures",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "teamAllocation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRequiredSignatures",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_SUPPLY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "TOKENS_PER_ETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyWithETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "communityAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeInitialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSignerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSignedWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialDistributionDone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marketingAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingMintableSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "teamAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRequiredSignatures",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequests",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "InitialDistributionCompleted(address,address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TokensPurchased(address,uint256,uint256)": EventFragment;
    "TokensSold(address,uint256,uint256)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "WithdrawalExecuted(uint256,uint256,address)": EventFragment;
    "WithdrawalRequested(uint256,uint256,address)": EventFragment;
    "WithdrawalSigned(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "InitialDistributionCompleted"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensPurchased"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensSold"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawalSigned"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  spender: string;
  value: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface InitialDistributionCompletedEventObject {
  teamWallet: string;
  marketingWallet: string;
  communityWallet: string;
}
export type InitialDistributionCompletedEvent = TypedEvent<
  [string, string, string],
  InitialDistributionCompletedEventObject
>;

export type InitialDistributionCompletedEventFilter =
  TypedEventFilter<InitialDistributionCompletedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TokensPurchasedEventObject {
  buyer: string;
  ethAmount: BigNumber;
  tokenAmount: BigNumber;
}
export type TokensPurchasedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokensPurchasedEventObject
>;

export type TokensPurchasedEventFilter = TypedEventFilter<TokensPurchasedEvent>;

export interface TokensSoldEventObject {
  seller: string;
  tokenAmount: BigNumber;
  ethAmount: BigNumber;
}
export type TokensSoldEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  TokensSoldEventObject
>;

export type TokensSoldEventFilter = TypedEventFilter<TokensSoldEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  value: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface WithdrawalExecutedEventObject {
  withdrawalId: BigNumber;
  amount: BigNumber;
  recipient: string;
}
export type WithdrawalExecutedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  WithdrawalExecutedEventObject
>;

export type WithdrawalExecutedEventFilter =
  TypedEventFilter<WithdrawalExecutedEvent>;

export interface WithdrawalRequestedEventObject {
  withdrawalId: BigNumber;
  amount: BigNumber;
  recipient: string;
}
export type WithdrawalRequestedEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  WithdrawalRequestedEventObject
>;

export type WithdrawalRequestedEventFilter =
  TypedEventFilter<WithdrawalRequestedEvent>;

export interface WithdrawalSignedEventObject {
  withdrawalId: BigNumber;
  signer: string;
}
export type WithdrawalSignedEvent = TypedEvent<
  [BigNumber, string],
  WithdrawalSignedEventObject
>;

export type WithdrawalSignedEventFilter =
  TypedEventFilter<WithdrawalSignedEvent>;

export interface YiDengToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: YiDengTokenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MAX_SUPPLY(overrides?: CallOverrides): Promise<[BigNumber]>;

    TOKENS_PER_ETH(overrides?: CallOverrides): Promise<[BigNumber]>;

    addSigner(
      newSigner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    buyWithETH(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    communityAllocation(overrides?: CallOverrides): Promise<[BigNumber]>;

    decimals(overrides?: CallOverrides): Promise<[number]>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    distributeInitialTokens(
      teamWallet: string,
      marketingWallet: string,
      communityWallet: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getSignerCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    hasSignedWithdrawal(
      requestId: BigNumberish,
      signer: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    initialDistributionDone(overrides?: CallOverrides): Promise<[boolean]>;

    isSigner(account: string, overrides?: CallOverrides): Promise<[boolean]>;

    marketingAllocation(overrides?: CallOverrides): Promise<[BigNumber]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    remainingMintableSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeSigner(
      signerToRemove: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requestWithdrawal(
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    requiredSignatures(overrides?: CallOverrides): Promise<[BigNumber]>;

    sellTokens(
      tokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    signWithdrawal(
      requestId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    signers(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    teamAllocation(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    updateRequiredSignatures(
      newRequiredSignatures: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    withdrawalId(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawalRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, boolean] & {
        amount: BigNumber;
        signatureCount: BigNumber;
        recipient: string;
        executed: boolean;
      }
    >;
  };

  MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

  TOKENS_PER_ETH(overrides?: CallOverrides): Promise<BigNumber>;

  addSigner(
    newSigner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  allowance(
    owner: string,
    spender: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

  buyWithETH(
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  communityAllocation(overrides?: CallOverrides): Promise<BigNumber>;

  decimals(overrides?: CallOverrides): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  distributeInitialTokens(
    teamWallet: string,
    marketingWallet: string,
    communityWallet: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getSignerCount(overrides?: CallOverrides): Promise<BigNumber>;

  hasSignedWithdrawal(
    requestId: BigNumberish,
    signer: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  initialDistributionDone(overrides?: CallOverrides): Promise<boolean>;

  isSigner(account: string, overrides?: CallOverrides): Promise<boolean>;

  marketingAllocation(overrides?: CallOverrides): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  remainingMintableSupply(overrides?: CallOverrides): Promise<BigNumber>;

  removeSigner(
    signerToRemove: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requestWithdrawal(
    amount: BigNumberish,
    recipient: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  requiredSignatures(overrides?: CallOverrides): Promise<BigNumber>;

  sellTokens(
    tokenAmount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  signWithdrawal(
    requestId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  signers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  symbol(overrides?: CallOverrides): Promise<string>;

  teamAllocation(overrides?: CallOverrides): Promise<BigNumber>;

  totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferFrom(
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  updateRequiredSignatures(
    newRequiredSignatures: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  withdrawalId(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawalRequests(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, boolean] & {
      amount: BigNumber;
      signatureCount: BigNumber;
      recipient: string;
      executed: boolean;
    }
  >;

  callStatic: {
    MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    TOKENS_PER_ETH(overrides?: CallOverrides): Promise<BigNumber>;

    addSigner(newSigner: string, overrides?: CallOverrides): Promise<void>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyWithETH(overrides?: CallOverrides): Promise<void>;

    communityAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    distributeInitialTokens(
      teamWallet: string,
      marketingWallet: string,
      communityWallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getSignerCount(overrides?: CallOverrides): Promise<BigNumber>;

    hasSignedWithdrawal(
      requestId: BigNumberish,
      signer: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialDistributionDone(overrides?: CallOverrides): Promise<boolean>;

    isSigner(account: string, overrides?: CallOverrides): Promise<boolean>;

    marketingAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    remainingMintableSupply(overrides?: CallOverrides): Promise<BigNumber>;

    removeSigner(
      signerToRemove: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requestWithdrawal(
      amount: BigNumberish,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    requiredSignatures(overrides?: CallOverrides): Promise<BigNumber>;

    sellTokens(
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    signWithdrawal(
      requestId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    signers(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    symbol(overrides?: CallOverrides): Promise<string>;

    teamAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRequiredSignatures(
      newRequiredSignatures: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawalId(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawalRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, boolean] & {
        amount: BigNumber;
        signatureCount: BigNumber;
        recipient: string;
        executed: boolean;
      }
    >;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: string | null,
      spender?: string | null,
      value?: null
    ): ApprovalEventFilter;
    Approval(
      owner?: string | null,
      spender?: string | null,
      value?: null
    ): ApprovalEventFilter;

    "InitialDistributionCompleted(address,address,address)"(
      teamWallet?: null,
      marketingWallet?: null,
      communityWallet?: null
    ): InitialDistributionCompletedEventFilter;
    InitialDistributionCompleted(
      teamWallet?: null,
      marketingWallet?: null,
      communityWallet?: null
    ): InitialDistributionCompletedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "TokensPurchased(address,uint256,uint256)"(
      buyer?: string | null,
      ethAmount?: null,
      tokenAmount?: null
    ): TokensPurchasedEventFilter;
    TokensPurchased(
      buyer?: string | null,
      ethAmount?: null,
      tokenAmount?: null
    ): TokensPurchasedEventFilter;

    "TokensSold(address,uint256,uint256)"(
      seller?: string | null,
      tokenAmount?: null,
      ethAmount?: null
    ): TokensSoldEventFilter;
    TokensSold(
      seller?: string | null,
      tokenAmount?: null,
      ethAmount?: null
    ): TokensSoldEventFilter;

    "Transfer(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      value?: null
    ): TransferEventFilter;
    Transfer(
      from?: string | null,
      to?: string | null,
      value?: null
    ): TransferEventFilter;

    "WithdrawalExecuted(uint256,uint256,address)"(
      withdrawalId?: BigNumberish | null,
      amount?: null,
      recipient?: null
    ): WithdrawalExecutedEventFilter;
    WithdrawalExecuted(
      withdrawalId?: BigNumberish | null,
      amount?: null,
      recipient?: null
    ): WithdrawalExecutedEventFilter;

    "WithdrawalRequested(uint256,uint256,address)"(
      withdrawalId?: BigNumberish | null,
      amount?: null,
      recipient?: null
    ): WithdrawalRequestedEventFilter;
    WithdrawalRequested(
      withdrawalId?: BigNumberish | null,
      amount?: null,
      recipient?: null
    ): WithdrawalRequestedEventFilter;

    "WithdrawalSigned(uint256,address)"(
      withdrawalId?: BigNumberish | null,
      signer?: null
    ): WithdrawalSignedEventFilter;
    WithdrawalSigned(
      withdrawalId?: BigNumberish | null,
      signer?: null
    ): WithdrawalSignedEventFilter;
  };

  estimateGas: {
    MAX_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    TOKENS_PER_ETH(overrides?: CallOverrides): Promise<BigNumber>;

    addSigner(
      newSigner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    balanceOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    buyWithETH(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    communityAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    decimals(overrides?: CallOverrides): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    distributeInitialTokens(
      teamWallet: string,
      marketingWallet: string,
      communityWallet: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getSignerCount(overrides?: CallOverrides): Promise<BigNumber>;

    hasSignedWithdrawal(
      requestId: BigNumberish,
      signer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    initialDistributionDone(overrides?: CallOverrides): Promise<BigNumber>;

    isSigner(account: string, overrides?: CallOverrides): Promise<BigNumber>;

    marketingAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    remainingMintableSupply(overrides?: CallOverrides): Promise<BigNumber>;

    removeSigner(
      signerToRemove: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requestWithdrawal(
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    requiredSignatures(overrides?: CallOverrides): Promise<BigNumber>;

    sellTokens(
      tokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    signWithdrawal(
      requestId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    signers(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    teamAllocation(overrides?: CallOverrides): Promise<BigNumber>;

    totalSupply(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    updateRequiredSignatures(
      newRequiredSignatures: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    withdrawalId(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawalRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_SUPPLY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOKENS_PER_ETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addSigner(
      newSigner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    allowance(
      owner: string,
      spender: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyWithETH(
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    communityAllocation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    distributeInitialTokens(
      teamWallet: string,
      marketingWallet: string,
      communityWallet: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getSignerCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasSignedWithdrawal(
      requestId: BigNumberish,
      signer: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    initialDistributionDone(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isSigner(
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    marketingAllocation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    remainingMintableSupply(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeSigner(
      signerToRemove: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requestWithdrawal(
      amount: BigNumberish,
      recipient: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    requiredSignatures(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sellTokens(
      tokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    signWithdrawal(
      requestId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    signers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    teamAllocation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transfer(
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    updateRequiredSignatures(
      newRequiredSignatures: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    withdrawalId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawalRequests(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
